---
- name: install dependencies for minc-toolkit
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - libc6
      - libstdc++6
      - imagemagick
      - perl

- name: download minc-toolkit
  get_url:
    url: http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/minc-toolkit-1.9.16-20180117-Ubuntu_16.04-x86_64.deb
    dest: /tmp

- name: install minc-toolkit
  apt:
    deb: /tmp/minc-toolkit-1.9.16-20180117-Ubuntu_16.04-x86_64.deb
