---
- name: install dependencies for minc-toolkit
  command: apt-get install -y libc6 libstdc++6 imagemagick perl

- name: download minc-toolkit
  command: wget http://packages.bic.mni.mcgill.ca/minc-toolkit/Debian/minc-toolkit-1.9.16-20180117-Ubuntu_16.04-x86_64.deb
  args:
    chdir: /tmp

- name: install minc-toolkit
  command: dpkg -i minc-toolkit-1.9.16-20180117-Ubuntu_16.04-x86_64.deb
  args:
    chdir: /tmp
